export function renderZshCompletion(): string {
  return [
    "#compdef pkit project-toolkit",
    "",
    "_pkit_skill_ids() {",
    "  local -a skills",
    "  skills=(\"${(@f)$(pkit skills list 2>/dev/null | sed 1d | awk '{print $1}')}\")",
    "  _describe 'skill' skills",
    "}",
    "",
    "_pkit_project_workspace_generate() {",
    "  _arguments -s -S \\",
    "    '--name[logical workspace name]:workspace name:' \\",
    "    '--root[target repository or worktree root]:directory:_files -/' \\",
    "    '--output[target workspace file path]:workspace file:_files'",
    "}",
    "",
    "_pkit_project_worktree_create() {",
    "  _arguments -s -S \\",
    "    '1:worktree name:' \\",
    "    '--branch[override branch name]:branch name:' \\",
    "    '--base[base ref for new branches]:git ref:' \\",
    "    '--workspace[override workspace name]:workspace name:' \\",
    "    '--output[output workspace file path]:workspace file:_files'",
    "}",
    "",
    "_pkit_project() {",
    "  local curcontext=\"$curcontext\" state",
    "  typeset -A opt_args",
    "",
    "  _arguments -C \\",
    "    '1:project command:(init workspace worktree)' \\",
    "    '*::project args:->project_args'",
    "",
    "  case $words[2] in",
    "    init)",
    "      _arguments '--force[rewrite scaffold files even if they already exist]'",
    "      ;;&",
    "    workspace)",
    "      case $words[3] in",
    "        generate)",
    "          _pkit_project_workspace_generate",
    "          ;;&",
    "        *)",
    "          _values 'workspace command' generate",
    "          ;;&",
    "      esac",
    "      ;;&",
    "    worktree)",
    "      case $words[3] in",
    "        create)",
    "          _pkit_project_worktree_create",
    "          ;;&",
    "        *)",
    "          _values 'worktree command' create",
    "          ;;&",
    "      esac",
    "      ;;&",
    "  esac",
    "}",
    "",
    "_pkit() {",
    "  local curcontext=\"$curcontext\" state",
    "  typeset -A opt_args",
    "",
    "  _arguments -C \\",
    "    '1:command:(skills project plan run dev auth completion)' \\",
    "    '*::args:->args'",
    "",
    "  case $words[1] in",
    "    skills)",
    "      _arguments '1:skills command:(list)'",
    "      ;;&",
    "    project)",
    "      _pkit_project",
    "      ;;&",
    "    plan|run)",
    "      _pkit_skill_ids",
    "      ;;&",
    "    dev)",
    "      _message 'pass through command arguments'",
    "      ;;&",
    "    auth)",
    "      _arguments '1:auth command:(status)'",
    "      ;;&",
    "    completion)",
    "      _arguments '1:shell:(zsh)'",
    "      ;;&",
    "  esac",
    "}",
    "",
    "_pkit \"$@\"",
    "",
  ].join("\n");
}
